### ISSUE TITLE
Segfault when providing a bad repository name with NCNN backend

### ISSUE THREAD

**Issue by BynaryCobweb** [jolibrain/deepdetect#610]
#### Configuration

- Version of DeepDetect: Locally compiled on Ubuntu 18.04 LTS
- Commit (shown by the server when starting): f9433a6da310b17d37cf0240fc46c5bc8b6b4b0d

#### Your question / the problem you're facing:

DeepDetect crashes with a segfault when creating a NCNN service with a wrong repository name.

#### Error message (if any) / steps to reproduce the problem:

```sh
curl -X PUT "http://localhost:8080/services/ncnn_bug" -d '{
    "description": "image classification service",
    "mllib": "ncnn",
    "model": {
        "repository": "./i-do-not-exist"
    },
    "parameters": {
        "input": {
            "connector": "image"
        }
    },
    "type": "supervised"
}
'
```
with `./i-do-not-exist` being a repository that does not exist.

Backtrace (gdb):

```
#0  0x000000000053597b in ncnn::Net::set_input_h(int) const ()
#1  0x00000000005037b6 in dd::NCNNLib<dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel>::init_mllib (this=this@entry=0x7fffda05e648, ad=...)
    at /home/louisj/deepdetect/src/backends/ncnn/ncnnlib.cc:77
#2  0x00000000004edf92 in dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel>::init (this=0x7fffda05e648, ad=...) at /home/louisj/deepdetect/src/mlservice.h:132
#3  0x00000000004ee125 in dd::visitor_init::operator()<dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel> > (mllib=..., this=0x7fffda058010)
    at /home/louisj/deepdetect/src/services.h:245
#4  mapbox::util::detail::dispatcher<dd::visitor_init&, mapbox::util::variant<dd::MLService<dd::NCNNLib, dd::CSVTSNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel>, dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel> >, void, dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel> >::apply (v=..., f=...)
    at /home/louisj/deepdetect/src/utils/variant.hpp:329
#5  0x00000000004f21e6 in mapbox::util::detail::dispatcher<dd::visitor_init&, mapbox::util::variant<dd::MLService<dd::NCNNLib, dd::CSVTSNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel>, dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel> >, void, dd::MLService<dd::NCNNLib, dd::CSVTSNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel>, dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel> >::apply (v=..., f=...) at /home/louisj/deepdetect/src/utils/variant.hpp:314
#6  0x00000000004f2215 in mapbox::util::variant<dd::MLService<dd::NCNNLib, dd::CSVTSNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel>, dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel> >::visit<dd::visitor_init&, mapbox::util::variant<dd::MLService<dd::NCNNLib, dd::CSVTSNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel>, dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel> >, void> (v=..., f=...) at /home/louisj/deepdetect/src/utils/variant.hpp:845
#7  0x00000000004f222e in mapbox::util::apply_visitor<dd::visitor_init&, mapbox::util::variant<dd::MLService<dd::NCNNLib, dd::CSVTSNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel>, dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel> > > (f=..., v=...) at /home/louisj/deepdetect/src/utils/variant.hpp:924
#8  0x00000000004f2318 in dd::Services::add_service(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mapbox::util::variant<dd::MLService<dd::NCNNLib, dd::CSVTSNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel>, dd::MLService<dd::NCNNLib, dd::ImgNCNNInputFileConn, dd::SupervisedOutput, dd::NCNNModel> >&&, dd::APIData const&) (this=this@entry=0x7fffffffe3b0, 
    sname="torchtest", mls=mls@entry=<unknown type in /home/louisj/deepdetect/build/main/dede, CU 0x705a4b, DIE 0x97bdad>, ad=...) at /home/louisj/deepdetect/src/services.h:333
#9  0x00000000004c96d6 in dd::JsonAPI::service_create (this=0x7fffffffe3b0, sname="torchtest",
    jstr="{\n    \"description\": \"image classification service\",\n    \"mllib\": \"ncnn\",\n    \"model\": {\n        \"repository\": \"./faces_embedded\"\n    },\n    \"parameters\": {\n        \"input\": {\n", ' ' <repeats 12 times>, "\"connector\":"...) at /home/louisj/deepdetect/src/jsonapi.cc:511
#10 0x00000000004b53a4 in APIHandler::operator() (this=0x7fffffffce00, request=..., response=...) at /home/louisj/deepdetect/src/httpjsonapi.cc:382
```

**Comment by fantes** [comment]
should be fixed by https://github.com/jolibrain/deepdetect/pull/613

**Comment by fantes** [comment]
thanks a lot for the bug report !
